// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ProductStore
{
    public partial class ProductStoreController
    {
        /// <summary>
        /// model input class for ProductStoreController.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"ProductID")]
            public float ProductID { get; set; }

            [ColumnName(@"ProductName")]
            public string ProductName { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Category")]
            public string Category { get; set; }

            [ColumnName(@"IsPopular")]
            public float IsPopular { get; set; }

            [ColumnName(@"Rating")]
            public float Rating { get; set; }

            [ColumnName(@"Reviews")]
            public float Reviews { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ProductStoreController.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ProductID")]
            public float ProductID { get; set; }

            [ColumnName(@"ProductName")]
            public float[] ProductName { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Category")]
            public float[] Category { get; set; }

            [ColumnName(@"IsPopular")]
            public uint IsPopular { get; set; }

            [ColumnName(@"Rating")]
            public float Rating { get; set; }

            [ColumnName(@"Reviews")]
            public float Reviews { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ProductStoreController.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
